name: 'Ketryx'
description: 'Send build results to Ketryx'
author: 'Ketryx'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: check-square
  color: green
inputs:
  ketryx-url:
    required: false
    description: 'Ketryx server URL'
    default: 'https://app.ketryx.com'
  project:
    required: true
    description: 'Ketryx project ID'
  version:
    required: false
    description: 'Ketryx version ID (if not set, the build will be associated with a version based on the commit SHA)'
  commit-sha:
    required: false
    description: 'Commit SHA (if not set, will use the environment variable GITHUB_SHA provided by GitHub Actions)'
  api-key:
    required: true
    description: 'Ketryx API key'
  build-name:
    required: false
    description: 'Build name to disambiguate several parallel builds'
  log:
    required: false
    description: 'Log output to store with the build'
  artifact-path:
    required: false
    description: 'Paths (newline-separated glob patterns) of build artifact files'
  test-cucumber-path:
    required: false
    description: 'Paths (newline-separated glob patterns) of Cucumber JSON files containing test results'
  test-junit-path:
    required: false
    description: 'Paths (newline-separated glob patterns) of JUnit XML files containing test results'
  check-dependencies-status:
    required: false
    description: 'Checks the status of dependencies, and fails the build if not all dependencies in the current commit are accepted and controlled'
    default: 'false'
  check-release-status:
    required: false
    description: 'Checks the status of the given version or the version(s) corresponding to the current commit, and fails the build if the versions are not all released'
    default: 'false'
outputs:
  ok:
    description: 'Whether sending the build to Ketryx and any included checks were successful'
  error:
    description: 'Error description, in case the build was not OK'
  build-id:
    description: 'Ketryx ID of the reported build'
