name: 'Ketryx'
description: 'Send build results to Ketryx'
author: 'Ketryx'
inputs:
  ketryxUrl:
    required: false
    description: 'Ketryx server URL'
    default: 'https://app.ketryx.com'
  project:
    required: true
    description: 'Ketryx project ID'
  version:
    required: false
    description: 'Ketryx version ID (if not set, the build will be associated with a version based on the commit SHA)'
  commitSha:
    required: false
    description: 'Commit SHA (if not set, will use the environment variable GITHUB_SHA provided by GitHub Actions)'
  apiKey:
    required: true
    description: 'Ketryx API key'
  buildName:
    required: false
    description: 'Build name to disambiguate several parallel builds'
  log:
    required: false
    description: 'Log output to store with the build'
  testCucumberPath:
    required: false
    description: 'Path of a Cucumber JSON file containing test results'
runs:
  using: 'node16'
  main: 'dist/index.js'
